### ISSUE TITLE
ImportError: cannot import name 'SyncClient' from 'scrapegraph_py'

### ISSUE THREAD

**Issue by aleenprd** [ScrapeGraphAI/Scrapegraph-ai#840]
**Describe the bug**
All of a sudden today I am getting this bug. I tried using version 1.33.1, now I am using 1.32.0, still the same thing. What am I supposed to do to solve this?
```
[2024-12-06, 15:22:41 UTC] {pod_manager.py:418} INFO - [base]     from scrapegraphai.graphs import SmartScraperGraph
[2024-12-06, 15:22:41 UTC] {pod_manager.py:418} INFO - [base]   File "/usr/local/lib/python3.10/site-packages/scrapegraphai/graphs/__init__.py", line 7, in <module>
[2024-12-06, 15:22:41 UTC] {pod_manager.py:418} INFO - [base]     from .smart_scraper_graph import SmartScraperGraph
[2024-12-06, 15:22:41 UTC] {pod_manager.py:418} INFO - [base]   File "/usr/local/lib/python3.10/site-packages/scrapegraphai/graphs/smart_scraper_graph.py", line 16, in <module>
[2024-12-06, 15:22:41 UTC] {pod_manager.py:418} INFO - [base]     from scrapegraph_py import SyncClient
[2024-12-06, 15:22:41 UTC] {pod_manager.py:418} INFO - [base] ImportError: cannot import name 'SyncClient' from 'scrapegraph_py' (/usr/local/lib/python3.10/site-packages/scrapegraph_py/__init__.py)
[2024-12-06, 15:22:41 UTC] {pod_manager.py:558} ERROR - Error parsing timestamp (no timestamp in message ''). Will continue execution but won't update timestamp
[2024-12-06, 15:22:41 UTC] {pod_manager.py:418} INFO - [base] 
```

**To Reproduce**
Just invoke this code: ```from scrapegraphai.graphs import SmartScraperGraph```

**Expected behavior**
That the import works.

**Desktop (please complete the following information):**
 - OS: Linux server (Ubuntu)

**Comment by 1KuuhaKu1** [comment]
I have the same problem!

**Comment by glebbadzeika** [comment]
Same

**Comment by dev-kasibhatla** [comment]
Roll back for now
```
pip install scrapegraphai==1.31.0
```

**Comment by 1KuuhaKu1** [comment]
> Roll back for now
> 
> ```
> pip install scrapegraphai==1.31.0
> ```

Many thanks! It's already resolved.

**Comment by VinciGit00** [comment]
Does it work with pip install scrapegraphai==1.33.2?
